//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EindOpdracht_Csharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class weatherdata
    {
        public weatherdata()
        {
            this.weatherdatacondition = new HashSet<weatherdatacondition>();
        }
    
        public long id { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
    
        public virtual ICollection<weatherdatacondition> weatherdatacondition { get; set; }
    }
}
