//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EindOpdracht_Csharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class weatherdatacondition
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public long weatherDataId { get; set; }
        public sbyte temparature { get; set; }
        public byte humididy { get; set; }
        public int windDirection { get; set; }
        public int windSpeed { get; set; }
        public string text { get; set; }
        public byte code { get; set; }
    
        public virtual weatherdata weatherdata { get; set; }
    }
}
